### PR TITLE
added function and passing test

### PR DESCRIPTION
**Pull request by danirenae**
## Related Issue

I fixed the bug at issue #8 

## Version

Node version v6.3.0
npm v 3.10.3
library version 1.0

## Documentation

There is new documentation in the README.md file

### CODE REVIEW

**Review by abbyfleming — APPROVED** [review]
No errors thrown, thanks for the contribution!

**Comment by consumerike** [comment]
You contributed! 🍼

**Comment by abbyfleming** [comment]
@itsdanirenae ! 🎉 🌮

**Comment by mshenfield** [comment]
🍌

**Pull request merged**
